export type StockDocument = {
  amount_in_units: number,
  archived: boolean,
  barcode: string,
  category_id: number,
  category_name: string,
  date: Date,
  expire_date: Date,
  item_id: number,
  item_name: string,
  item_note: string,
  pc_barcode: "12340",
  pc_cost: number,
  pc_price: number,
  pc_unit_id: number,
  pc_unit_name: string,
  pcs_per_unit: number,
  production_date: null,
  stocking_id: number,
  stocking_note: string,
  total_available_pcs: number,
  total_available_units: number,
  unit_cost: number,
  unit_id: number,
  unit_name: string,
  unit_price: number,
  user_id: number,
}

